<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

class GatewayAvailability extends BaseConfig
{
    /**
     * Technical timestamps are generated by PHP in Bolivia time. Availability
     * calculations must not depend on the database session timezone.
     */
    public string $displayTimezone = 'America/La_Paz';

    public int $onlineThresholdSeconds = 120;
    public int $delayedThresholdSeconds = 600;
    public int $availabilityLeaseSeconds = 120;
    public int $pendingSmsWindowSeconds = 300;
    public int $fcmTtlSeconds = 120;
}
